"""Build two renamed OFL webfont subsets from rendered site text.

Requires fonttools[woff] and brotli. Keep the original v1.3.9 font outside Git.
Usage: python scripts/subset-fonts.py --source SOURCE.woff2 --html-root dist
"""
import argparse
import hashlib
import json
from html.parser import HTMLParser
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


class VisibleText(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.ignored = 0
        self.chars = set()

    def handle_starttag(self, tag, attrs):
        if tag in {"script", "style"}:
            self.ignored += 1
        if not self.ignored:
            for name, value in attrs:
                if name in {"placeholder", "aria-label", "alt", "title"} and value:
                    self.chars.update(map(ord, value))

    def handle_endtag(self, tag):
        if tag in {"script", "style"}:
            self.ignored = max(0, self.ignored - 1)

    def handle_data(self, data):
        if not self.ignored:
            self.chars.update(map(ord, data))


def characters(file):
    parser = VisibleText()
    parser.feed(file.read_text(encoding="utf-8"))
    return parser.chars


def unicode_range(chars):
    runs = []
    for cp in sorted(chars):
        if runs and cp == runs[-1][1] + 1:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp])
    return ",".join(f"U+{a:X}" if a == b else f"U+{a:X}-{b:X}" for a, b in runs)


def build_font(source, chars, output):
    font = TTFont(source)
    options = subset.Options()
    options.flavor = "woff2"
    options.name_IDs = ["*"]
    options.name_legacy = True
    options.name_languages = ["*"]
    sub = subset.Subsetter(options=options)
    sub.populate(unicodes=chars)
    sub.subset(font)
    # Modified fonts must not use the upstream reserved family name.
    for name in font["name"].names:
        if name.nameID in {1, 3, 4, 6, 16, 25}:
            value = "NoblesseUI-Regular" if name.nameID in {3, 6, 25} else "Noblesse UI"
            name.string = value.encode(name.getEncoding())
        elif name.nameID > 255:
            name.string = name.toUnicode().replace("PretendardVariable", "NoblesseUI").encode(name.getEncoding())
    font.flavor = "woff2"
    font.save(output)
    generated = TTFont(output)
    assert chars <= set(generated.getBestCmap()), "Subset lost required characters"
    weight = next(axis for axis in generated["fvar"].axes if axis.axisTag == "wght")
    assert weight.minValue <= 100 and weight.maxValue >= 900


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--html-root", type=Path, default=Path("dist"))
    args = parser.parse_args()
    assert hashlib.sha256(args.source.read_bytes()).hexdigest() == "9599f12fd42fc0bce1cd50b47a0c022e108d7aa64dd0d1bb0ed44f3282d900b4", "Use the pinned Pretendard v1.3.9 source"
    root = Path(__file__).resolve().parents[1]
    files = sorted(args.html_root.rglob("*.html"))
    assert len(files) >= 159, "Build all site pages before generating font subsets"
    supported = set(TTFont(args.source).getBestCmap())
    all_chars = set(range(32, 127))
    for file in files:
        all_chars.update(characters(file))
    # Home plus common navigation/text loads without the remaining guide glyphs.
    home = (characters(args.html_root / "index.html") | set(range(32, 127))) & supported
    rest = (all_chars & supported) - home
    output = root / "public" / "fonts"
    output.mkdir(exist_ok=True)
    css = ["/* Generated by scripts/subset-fonts.py; OFL source/license: /fonts/OFL.txt */"]
    manifest = {"source": "Pretendard v1.3.9", "source_sha256": hashlib.sha256(args.source.read_bytes()).hexdigest(), "html_files": len(files), "subsets": []}
    for label, chars in [("home", home), ("content", rest)]:
        file = output / f"noblesse-ui-{label}.woff2"
        build_font(args.source, chars, file)
        css.append(f"@font-face {{\n  font-family: 'Noblesse UI';\n  font-style: normal;\n  font-weight: 100 900;\n  font-display: swap;\n  src: url('/fonts/{file.name}') format('woff2');\n  unicode-range: {unicode_range(chars)};\n}}")
        manifest["subsets"].append({"file": file.name, "characters": len(chars), "bytes": file.stat().st_size})
    (root / "assets" / "css" / "fonts.css").write_text("\n\n".join(css) + "\n", encoding="utf-8")
    (output / "manifest.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
